apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-bank
  template:
    metadata:
      labels:
        app: my-bank
    spec:
      containers:
      - name: banking-app
        image: suyash28/banking-app:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: my-bank-service
spec:
  selector:
    app: my-bank
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer   